export TAVERNA_HOME="/home/yousee/taverna/taverna-workbench-2.4.0"
export JAVA_HOME="/usr/java/jdk1.6.0_32"

export YOUSEE_HOME="$HOME/yousee-workflow/services/workflow"
export YOUSEE_CONFIG="${yousee.config}"
export YOUSEE_WORKFLOW_CONFIG="${yousee.workflow.config}"
export YOUSEE_LOGS="$HOME/${yousee.logs}"
export YOUSEE_LOCKS="$HOME/var/${yousee.locks}"
export YOUSEE_COMPONENTS="${yousee.home}/${yousee.components.dir}"
export YOUSEE_SCRIPTS="${yousee.home}/${yousee.script.dir}"
export YOUSEE_WORKFLOWS="${yousee.home}/${yousee.workflow.dir}"
export YOUSEE_DEPENDENCIES="${yousee.home}/${yousee.workflow.dependencies}"
export YOUSEE_BIN="${yousee.home}/${yousee.bin}"
